### ISSUE TITLE
Debuggee never connects

### ISSUE THREAD

**Issue by bananabr** [4d61726b/VirtualKD-Redux#41] opened 2022-01-12 00:19 UTC
**Describe the bug**
Debuggee never connects to debug pipe.

**To Reproduce**
Follow the installation tutorial using the configuration below.

**Expected behavior**
Debuggee connects to pipe and debugger breaks execution.

**Screenshots**

![VirtualKD](https://user-images.githubusercontent.com/9096933/149041634-aa76149f-6f8a-431d-8931-d7b7ab7e940a.gif)

**Configuration (please complete the following information):**
 - VirtualKD-Redux version [e.g. 2019.4]: 2021.3
 - VMware or VirtualBox version [e.g. VMware Workstation 15.5.0 build-14665864]: VirtualBox 6.1.12 r139181 (Qt5.6.2)
 - OS running on the host [e.g. Windows 10 1903 64-bit]: Windows 10 10.0.19043 N/A Build 19043
 - OS running in the guest VM [e.g. Windows 7 SP1 32-bit]: Windows 10 10.0.17763 N/A Build 17763

**Comment by 4d61726b** [comment] 2022-01-12 00:34
Thanks for creating a good writeup and providing the animated GIF, that helps a lot.

I noticed that you didn't press F8 and disable driver signature enforcement at the boot menu. Would you be able to try that first before I start to triage this?

**Comment by bananabr** [comment] 2022-01-12 15:33
Sorry, @4d61726b,

It's my first time using VirtualKD. You are right; I was missing the F8 step. The problem now is that the VM will hang forever on the Windows boot logo when the debugger is connected.

![image](https://user-images.githubusercontent.com/9096933/149170882-9237ebe2-81a8-4963-85b1-a1a80c2aa537.png)


I know things are supposed to run slower with a debugger connected, but I let it run the whole night, and it's still stuck on the boot screen.

Thanks for your help,

**Comment by effolkronium** [comment] 2022-01-12 15:48
Probably it’s stopped in debugger mode. I should type “g” command in windbg to continue

**Comment by bananabr** [comment] 2022-01-12 19:53
I thought I did that already, but I will try that in a few and let you know the results.

**Comment by bananabr** [comment] 2022-01-12 19:58
You can see the debuggee was already running in my last screenshot, but here is a new one anyway. CPU seems to be active be the VM is stuck in the boot screen.

![image](https://user-images.githubusercontent.com/9096933/149212643-8ab7c5ff-b854-445d-ba86-c93e1f0dfabc.png)

**Comment by bananabr** [comment] 2022-01-12 20:07
Just realized that even if I don't have vmmon running, nor a debugger, the VM won't start if the driver signature requirement is disabled.

**Comment by 4d61726b** [comment] 2022-01-22 15:53
@bananabr 

Apologies, I have not had any free time yet to sit down and triage the cause of this issue. In the meantime, I might have a temporary workaround for you. Would you mind bumping the guest RAM down from 4096 to 2048 and seeing if that makes a difference? After making that change you should just need to boot again, press F8, and then select the option to disable driver signature enforcement.

You should then get the initial break in during boot and then after issuing the "g" command, the system should immediately continue booting.

**Comment by chbest0102** [comment] 2022-01-24 07:52
After decrease RAM from 4096 to 2048 in VMware, it still not work, it's still stuck on the boot screen.

**Comment by RiabovAndrew** [comment] 2022-02-08 13:11
The easiest way to solve this bug is to reset virtual machine to the previous snapshot.

BTW, I tried to reinstall virtualKD on host and guest, but hadn't been gotten with any results. I use VMware, so this bug occurs on VMware too. XD

**Comment by 4d61726b** [comment] 2022-08-30 02:41
@bananabr @chbest0102 @RiabovAndrew 

I've made several stability fixes in VirtualKD-Redux since this issue was filed. Since I've never been able to personally reproduce the problem described, would someone be able to try **VirtualKD-Redux 2022.1** to see if that version addresses the problem?

For a proper test, it's **critical** that you rerun `vminstall.exe` from **2022.1** on the guest. You cannot use the `vminstall.exe` from an older version as that won't have all the fixes.

For an accurate test (and to reduce the chance of human error), I think it's best to just try this on a virtual machine that has never had VirtualKD-Redux ever installed.

**Comment by 4d61726b** [comment] 2022-09-14 02:12
I'm going to close this out for now, but if the issue still persists with the latest version, feel free to comment on this ticket with details.

**Closed by 4d61726b** 2022-09-14 02:12 UTC
