### ISSUE TITLE
Windows Server 2003R2 x86 BSOD

### ISSUE THREAD

**Issue by alexweb01** [4d61726b/VirtualKD-Redux#18] opened 2020-07-25 10:01 UTC
Hi,
Can't using your mod on Windows Server 2003R2 x86 (en_win_srv_2003_r2_enterprise_x64_with_sp2_vl_cd1_x13-48614.iso)
The BSOD happened on logging in.
Reinstalling the OS is not helped.

00 ba6085f8 80826c77 00000003 00000002 00000000 nt!RtlpBreakWithStatusInstruction
01 ba608644 80827b84 00000003 00000000 e2571a98 nt!KiBugCheckDebugBreak+0x19
02 ba6089dc 80827f7d 00000044 e2571a98 00000d7c nt!KeBugCheck2+0x5ea
03 ba6089fc 8081e54d 00000044 e2571a98 00000d7c nt!KeBugCheckEx+0x1b
04 ba608a34 f75ead33 8f3e01a8 8ff5b460 ba608a58 nt!IopfCompleteRequest+0x2f7
05 ba608a44 8081e185 902ca2b8 900d8f28 900d8f28 termdd!IcaDispatch+0x13d
06 ba608a58 808fb411 ba608c04 902ca2a0 00000000 nt!IofCallDriver+0x45
07 ba608b40 80939f4d 902ca2b8 00000000 8f3ee9d8 nt!IopParseDevice+0xa35
08 ba608bc4 80936066 00000000 ba608c04 00000040 nt!ObpLookupObjectName+0x5c1
09 ba608c18 808ed0b5 00000000 00000000 00000001 nt!ObOpenObjectByName+0xea
0a ba608c94 808ee36b 000b3204 c0100000 00c9f538 nt!IopCreateFile+0x447
0b ba608cf0 808f0faa 000b3204 c0100000 00c9f538 nt!IoCreateFile+0xa3
0c ba608d30 8088b658 000b3204 c0100000 00c9f538 nt!NtCreateFile+0x30
0d ba608d30 7c8283ac 000b3204 c0100000 00c9f538 nt!KiSystemServicePostCall
0e 00c9f500 7c826ba9 74d9121e 000b3204 c0100000 ntdll!KiFastSystemCallRet
0f 00c9f504 74d9121e 000b3204 c0100000 00c9f538 ntdll!NtCreateFile+0xc
10 00c9f560 74d9148b 000b3204 0009e8b0 00000032 ICAAPI!_IcaOpen+0x59
11 00c9f580 74d923a7 000001c0 000b3204 00000001 ICAAPI!_IcaStackOpen+0x78
12 00c9f5a4 7655b2f3 000001c0 00000003 00000000 ICAAPI!IcaChannelOpen+0x41
13 00c9f6d4 76552263 000afe48 00c9fd10 00c9f8a0 termsrv!WaitForConsoleConnectWorker+0x144
14 00c9f858 765567bb 00000000 00000170 00000001 termsrv!WinStationNotifyLogonWorker+0x3db
15 00c9f89c 77c80125 0009e930 00c9fcc0 00000000 termsrv!RpcWinStationNotifyLogon+0x9e
16 00c9f8f0 77ce53e1 7655671d 00c9fae0 00000010 RPCRT4!Invoke+0x30
17 00c9fcf8 77ce55c4 00000000 00000000 0009ebe4 RPCRT4!NdrStubCall2+0x299
18 00c9fd14 77c7ff0a 0009ebe4 000b8f48 0009ebe4 RPCRT4!NdrServerCall2+0x19
19 00c9fd48 77c803bf 7656f984 0009ebe4 00c9fdec RPCRT4!DispatchToStubInCNoAvrf+0x38
1a 00c9fd9c 77c802e5 00000020 00000000 7657589c RPCRT4!RPC_INTERFACE::DispatchToStubWorker+0x11f
1b 00c9fdc0 77c8117d 0009ebe4 00000000 7657589c RPCRT4!RPC_INTERFACE::DispatchToStub+0xa3
1c 00c9fdfc 77c81291 0009e978 000b6280 000b7170 RPCRT4!LRPC_SCALL::DealWithRequestMessage+0x42c
1d 00c9fe20 77c88688 000b62b8 00c9fe38 0009e978 RPCRT4!LRPC_ADDRESS::DealWithLRPCRequest+0x127
1e 00c9ff84 77c887a2 00c9ffac 77c8873d 000b6280 RPCRT4!LRPC_ADDRESS::ReceiveLotsaCalls+0x430
1f 00c9ff8c 77c8873d 000b6280 00000000 00000000 RPCRT4!RecvLotsaCallsWrapper+0xd
20 00c9ffac 77c7b03e 0009b070 00c9ffec 77e6484f RPCRT4!BaseCachedThreadRoutine+0x9d
21 00c9ffb8 77e6484f 000b6360 00000000 00000000 RPCRT4!ThreadStartRoutine+0x1b
22 00c9ffec 00000000 77c7b023 000b6360 00000000 kernel32!BaseThreadStart+0x34

**Comment by 4d61726b** [comment] 2020-07-27 03:08
You mentioned that it happened on your 32-bit OS but the ISO you said you were using is the 64-bit version.

I have the physical media for Windows Server 2003 R2 32-bit and tried it with the latest version of VirtualKD-Redux. Everything worked fine for me. Perhaps your ISO is corrupted.

**What version of VMware Workstation are you running?
How is the VM configured (e.g. processor and memory configuration)?
What kind of processor do you have (i.e. Intel or AMD, and what model)?
Does it BSOD after an Easy Install?
Did you install VMware Tools in the VM?**

I don't believe this is an issue with VirtualKD-Redux. I don't see kdbazis in your call stack, though its possible that kdbazis caused some memory corruption that would manifest itself like that. What was the bug check code?

**Comment by alexweb01** [comment] 2020-07-27 11:11
Sorry messed up the iso image name.
en_win_srv_2003_r2_enterprise_with_sp2_vl_cd1_x13-48610.iso
SHA1:0D0CDDD29FCF8FF7456A4BE8CE15698EBA90D1DC
Hash matches the msdn original.
Vnware: 15.5.6 build-16341506
vmware config:
processors: 1 
cores per proc: 4
RAM: 1GB
HDD: 4GB
Network: NAT
VMWare Tools installed
The BSOD happened while logging in (after CtrlAltDel) - Multiple IRP complete requests

With datacenter edition working good.
The problem is in enterprise edition..

**Comment by 4d61726b** [comment] 2020-07-27 14:29
Is there anything that you do to the VM after the OS install, besides install VMware Tools and install VirtualKD-Redux? For example, do you add or configure any server roles?

**Comment by alexweb01** [comment] 2020-07-27 14:49
No additional modification to the OS.
Here is the steps to reproduce:
1) Install OS
2) Install VMWare Tools
3) Install VirtualKD-Redux
4) Reboot
5) Enter login/password
6) Winlogon processing and BSOD in the termdd.sys driver

**Comment by 4d61726b** [comment] 2020-07-28 03:18
I've been trying to reproduce this but have not been able to. I used the same VM configuration, OS, and followed your steps.

Based on your call stack, the bug check code at nt!IopfCompleteRequest+0x2f7 is 0x44 which is MULTIPLE_IRP_COMPLETE_REQUESTS. The kernel component of VirtualKD-Redux (kdbazis) does not do anything with I/O request packets so it's not possible that it ever called IoCompleteRequest. The kdpatch component interacted with the I/O manager but that has been deprecated.

How did you install VirtualKD-Redux in the VM? Did you use kdpatch or vminstall? Are you using 2020.2?

Does everything work if VirtualKD-Redux is installed in the VM but you select the standard boot option?

**Comment by alexweb01** [comment] 2020-07-28 08:50
If I boot without VirtualKD all going good
VirtualKD-Redux 2020.2
Install by vminstall
I have been solve this problem by installing an other image.
Thank you!

**Comment by 4d61726b** [comment] 2020-09-19 01:23
Closing issue since I still am unable to reproduce it and user has a workaround.

**Closed by 4d61726b** 2020-09-19 01:23 UTC
