### ISSUE TITLE
Virtual box doesn't boot windows 11 when i load with "Disable Driver Signature Enforcement" option

### ISSUE THREAD

**Issue by parchinskiy** [4d61726b/VirtualKD-Redux#56] opened 2023-11-08 19:17 UTC
**Describe the bug**
Hello, can you help me? I'm trying to activate debugging according to the instructions
https://github.com/4d61726b/VirtualKD-Redux/blob/master/VirtualKD-Redux/Docs/Tutorial.md
When I do step 4 from section [Guest VM](https://github.com/4d61726b/VirtualKD-Redux/blob/master/VirtualKD-Redux/Docs/Tutorial.md#guest-vm) virtual box freezes. If I wait 5-10 minutes, the automatic recovery windows appear.

**To Reproduce**
1)Run vminstall.exe from target64 folder on guest os
2)Select options "Replace kdcom.dll"
3)Restart Guest
4)Select "Disable Driver Signature Enforcement" and boot
5)Gues OS doesn't boot

**Expected behavior**
OS boots successfully

**Screenshots**
State in which loading stops
![image](https://github.com/4d61726b/VirtualKD-Redux/assets/30821523/7480bd62-4e3e-4f20-90c3-19e7b8d7448d)

**Configuration (please complete the following information):**
 - I try VirtualKD Redux 2023.0 and 2022.2
 - VirtualBox version 7.0.12r159484
 - OS running on the host Windows 11 22621.2506
 - OS running in the guest Windows 11 22631.2428

**Comment by 4d61726b** [comment] 2023-11-10 21:32
You seem to be missing a few steps. Did you add the certificate, setup `VirtualBox7_Integration.exe`, and run `vmmon64.exe` on your host?

https://github.com/4d61726b/VirtualKD-Redux/blob/master/VirtualKD-Redux/Docs/Tutorial.md#host-virtualbox-only
https://github.com/4d61726b/VirtualKD-Redux/blob/master/VirtualKD-Redux/Docs/Tutorial.md#host-final-steps

**Comment by 4d61726b** [comment] 2023-11-19 18:42
I'm assuming this was addressed with my last suggestion so I'm closing it for now

**Closed by 4d61726b** 2023-11-19 18:42 UTC

**Comment by giudon010** [comment] 2023-12-03 16:02
> In your **guest VM** can you:
> 
>     1. Boot into Windows normally, no debugging
> 
>     2. Right click `kdcom.dll` in `C:\Windows\System32`
> 
>     3. Click `Properties`
> 
>     4. Click the `Details` tab
> 
>     5. Screenshot and post it here
> 
> 
> Additionally, can you run `winver` in your **guest VM** and post the screenshot here as well?
> 
> What version of VirtualBox are you running?

kdcom version details inside guest:
<img width="201" alt="VirtualBoxVM_DnelBLBRLs" src="https://github.com/4d61726b/VirtualKD-Redux/assets/58396344/ea4958a0-1b9e-48a5-b422-0f0e903b2c84">

Winver inside guest:
<img width="123" alt="VirtualBoxVM_5fqndlChJo" src="https://github.com/4d61726b/VirtualKD-Redux/assets/58396344/ed227d83-b402-4d52-b437-8f3a40e368c7">

VirtualBox Version:
![immagine](https://github.com/4d61726b/VirtualKD-Redux/assets/58396344/b978de46-6436-4d0b-b66a-f226d75c0c41)

**Comment by 4d61726b** [comment] 2023-12-03 19:21
Thanks for the info. I was able to reproduce this issue with your environment.

I would need some time to try and triage this, but it may be a while until I get to it. In the meantime, you can always use Windows 11 on VMware Workstation. That still works perfectly.

VirtualBox has always been a second-class citizen on this project because it's not something I ever use.

**Comment by SoleimanyBen** [comment] 2023-12-04 00:17
@4d61726b I'm running into the same issue on VMWare Workstation with my VM running Windows 11.

I went ahead and reduced my VMs memory to 2048mb, but it still just hangs on startup. If I don't try and boot the OS with driver signature enforcement enabled, the OS boots just fine.

I also checked my `kdcom.dll` details, and it matches what @giudon010 posted.

**Comment by giudon010** [comment] 2023-12-04 14:59
> @giudon010 I had some free time to look into this and track down the problem. At first glance, it appears that there is a discrepancy between the monitor and the guest with regard to the physical address of the buffer that holds the RPC channel data in the guest.
> 
> As a temporary workaround, can you reduce the memory to 2048mb in the guest and let me know if you are able to get further?

The workaround works!!! Thank you for your time and work @4d61726b

**Comment by SoleimanyBen** [comment] 2023-12-04 15:02
> @SoleimanyBen I have not yet been able to reproduce this symptom in VMware Workstation. The issue experienced here is in the VirtualBox part of the code which is not shared with VMware Workstation.
> 
>     1. What version of VMware Workstation are you running?
> 
>     2. Can you give me the Windows version in the guest from `winver`?
> 
>     3. Do you have Hyper-V enabled on your host? The easiest way to determine this is if you go to your Virtual Machine settings, click the "Options" tab, and select "Advanced". Look for the following:
> 
> 
> <img alt="image" width="429" src="https://private-user-images.githubusercontent.com/55967456/287574211-1c820c04-6bea-48df-aed7-4a0f7cf09690.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MDIzNDgsIm5iZiI6MTcwMTcwMjA0OCwicGF0aCI6Ii81NTk2NzQ1Ni8yODc1NzQyMTEtMWM4MjBjMDQtNmJlYS00OGRmLWFlZDctNGEwZjdjZjA5NjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDE1MDA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViZjJhZWQyNmM3MDc4Y2NjZDRkYzIwNzI2MjlmNzZlZGEwNjQ1NDZjZGRhMTJkY2Y5Nzc2OGE5ZDE5NzUyNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H7m5W5LJnlyMEwcmhsA06wTXBsBcTbN8S9-cKQ9a30k">
> 
> Regardless of whether it's selected or not, then the answer is "Yes". If you don't even see that option available, then the answer is "No".

@4d61726b Thank you for the reply :)

It actually turns out that it was an old version of VMWare Workstation that was causing the issue. I am not entirely sure what version of VMWare Workstation I was previously on, but once I upgraded to `17.5.0 build-22583795` everything worked as was expected.

**Comment by 4d61726b** [comment] 2024-03-03 17:18
This issue has been addressed in 2024.0. Running the new `vminstall.exe` in Windows 11 now has the option to patch `winload` which will force it to map the early boot modules into a lower physical address range.

The issue was that `kdcom.dll` was getting physically mapped to a range where the upper half of the address were not all zeroes. This broke the VirtualBox RPC mechanism.

The end result of this fix will allow you to run Windows 11 with any amount of RAM configured. You will no longer need to set it to a low value that previously suggested as a workaround.
