### ISSUE TITLE
VirtualBoxIntegration crash

### ISSUE THREAD

**Issue by chuangshizhiqiang** [4d61726b/VirtualKD-Redux#32] opened 2021-05-25 12:44 UTC
My system is  WIN10 20H2  19042.985 X64

![1](https://user-images.githubusercontent.com/16714437/119499891-c3f21400-bd99-11eb-9bd0-7abd6ce18623.jpg)

**Comment by 4d61726b** [comment] 2021-05-26 02:11
What version of VirtualBox are you running? My guess is that this issue would be addressed if you use download and install the latest version (currently 6.1.22).

**Comment by 4d61726b** [comment] 2021-05-29 13:44
This issue should be resolved in VirtualKD-Redux 2021.2. More error checking and error messages have been added which should better indicate to the user what the problem is.

**Closed by 4d61726b** 2021-05-29 13:44 UTC
